<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $fillable = ['name', 'parent_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function parent()
    {
        return Category::where('id', $this->parent_id)->first();
    }

    public function childs()
    {
        return Category::where('parent_id', $this->id)->get();
    }

    public static function allToAccess(){

        $results = [];

        if (auth()->user()->hasRole('megaroot')){
            $results = Category::all();
        }else{
            $results = User::getAdmin()->categories->merge(auth()->user()->categories);
        }

        return $results;
    }

    public function delete()
    {
        Category::where('parent_id', $this->id)->delete();

        return parent::delete(); // TODO: Change the autogenerated stub
    }

}
